name: Deploy MTA to Cloud Foundry

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - uses: cloudfoundry-community/cf-html5-deploy-action@v1
        with:
          api: ${{ secrets.CF_API }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          organization: ${{ CF_ORG }}
          space: ${{ CF_SPACE }}
          appname: my-mta-app
