# Build Multitarget Application & Deploy it to Cloud Foundry
name: Build MTA & Deploy it to CF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load NPM dependencies
        run: yarn
      - name: Build UI5 Project
        run: yarn build
      - name: Build MTAR for CF Cloud
        run: |
          docker run -u root -v "$(pwd):/project" devxci/mbtci:latest mbt build -e dev.mtaext --mtar -p=cf -t ui5app.mtar
      - name: Deploy to Neo Cloud
        run: |
          docker run -u root -v ${PWD}:/project ppiper/neo-cli:latest neo.sh deploy-mta --host ${{ secrets.NEO_HOST }} --account ${{ secrets.NEO_ACCOUNT }} --source /project/ui5app.mtar --synchronous --user ${{ secrets.NEO_USER }} --password ${{ secrets.NEO_PASSWORD }}
