name: Deploy MTA to Cloud Foundry

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cloud Foundry CLI
        run: |
          sudo apt-get update
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install cf-cli
      - name: Login to Cloud Foundry
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: |
          cf api $CF_API
          cf login -u $CF_USERNAME -p $CF_PASSWORD
      - name: Build and push application to Cloud Foundry
        run: |
          cf deploy mta_archives\boilerplate_1.0.0.mtar -s my-space
