name: Deploy to Cloud Foundry HTML5 Managed Application Router

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Cloud Foundry CLI
        run: |
          apt-get update
          apt-get install -y wget
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          apt-get update
          apt-get install -y cf-cli
      - name: Login to Cloud Foundry
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: |
          cf api $CF_API
          cf login -u $CF_USERNAME -p $CF_PASSWORD
      - name: Build and push application to Cloud Foundry HTML5 Managed Application Router
        run: |
          cf push -f manifest.yml --vars-file vars.yml
