name: Build and Deploy MTA

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - uses: pivotal-cf/cf-cli@1.0.1
        with:
          api: ${{ secrets.CF_API }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          organization: ${{ secrets.CF_ORG }}
          space: ${{ secrets.CF_SPACE }}
          command: mta build
      - uses: pivotal-cf/cf-cli@1.0.1
        with:
          api: ${{ secrets.CF_API }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          organization: ${{ secrets.CF_ORG }}
          space: ${{ secrets.CF_SPACE }}
          command: mta deploy
