name: Build and Deploy MTA

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - uses: SAP/cloud-mta-cf-deployment-action@v1
        with:
          cf-api: ${{ secrets.CF_API }}
          cf-user: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}
          cf-space: ${{ secrets.CF_SPACE }}
          mta-file: my-mta.mtar
